import { chromium } from 'playwright';
const URL = 'http://localhost:8347/poc-sprites.html';
const browser = await chromium.launch();
const errs = [];
let page = await browser.newPage({ viewport: { width: 420, height: 800 }, deviceScaleFactor: 2 });
page.on('console', m => m.type() === 'error' && errs.push(m.text()));
page.on('pageerror', e => errs.push(e.message));
await page.goto(URL);
await page.waitForTimeout(1800);
await page.screenshot({ path: 'test/shots/sprites-mobile.png' });
await page.close();
page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1.5 });
await page.goto(URL);
await page.waitForTimeout(1800);
await page.screenshot({ path: 'test/shots/sprites-desktop.png' });
await browser.close();
console.log('sprite shots done; console errors:', errs.length ? errs.join('\n') : 'none');
